# Site settings
title: The Mekicha Blog 
email: emeka.icha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mekicha1
github_username:  mekicha 

# Build settings
sass:
    sass_dir: _sass
kramdown:
  input: GFM
include: ['_pages']
theme: kayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
